[build]
    publish = "public"
    command = "npm install node-fetch prompt"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
